import os
import json
import re
from datetime import datetime, timedelta
from core.config import Config

def generate_weekly_report():
    """ Generates a tactical markdown report for the last 7 days. """
    events_file = Config.NEXUS_EVENTS_LOG
    reports_dir = os.path.join(Config.DATA_PATH, "reports")
    os.makedirs(reports_dir, exist_ok=True)
    
    cutoff = datetime.now() - timedelta(days=7)
    stats = {'reqs': 0, 'fails': 0, 'bans': 0, 'ips': set()}
    
    try:
        if os.path.exists(events_file):
            with open(events_file, 'r', encoding='utf-8') as f:
                for line in f:
                    try:
                        ev = json.loads(line)
                        ev_ts = datetime.fromisoformat(ev['timestamp'])
                        if ev_ts > cutoff:
                            if ev['name'] == 'login_failed': stats['fails'] += 1
                            if ev['name'] == 'login_success': stats['reqs'] += 1
                            if 'von' in ev['data'].get('details', ''):
                                m = re.search(r'von ([\d\.]+)', ev['data'].get('details', ''))
                                if m: stats['ips'].add(m.group(1))
                    except: continue
    except: pass

    report_name = f"security_report_{datetime.now().strftime('%Y_%W')}.md"
    report_path = os.path.join(reports_dir, report_name)
    
    content = f"""# Nexus Tactical Security Audit - Week {datetime.now().strftime('%W, %Y')}
## 🛡️ Operational Summary
- **Audit Period**: {cutoff.strftime('%Y-%m-%d')} to {datetime.now().strftime('%Y-%m-%d')}
- **Total Success Logins**: {stats['reqs']}
- **Total Failed Attempts**: {stats['fails']}
- **Unique Attacking IPs**: {len(stats['ips'])}

## 🔴 Autonomous Containments
P.I.G.E.O.N. has successfully mitigated all detected threats within this period. 
Bans were issued based on Brute-Force heuristics and Rate-Limiting violations.

## 📝 Strategic Assessment
The system integrity remains **NOMINAL**. No unauthorized access detected.

*Generated by P.I.G.E.O.N. Intelligence Engine*
"""
    # Write individual report
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(content)
        
    # Update Master Report (Komplett-Status.md)
    update_master_status(stats, cutoff)
        
    return f"Wöchentlicher Bericht erstellt: {report_name}"

def update_master_status(stats, cutoff):
    """ Aggregates all tactical data into the master Komplett-Status.md file. """
    from core.models import User
    from app import app # Needed for DB context
    
    # Get User Stats
    user_count = 0
    with app.app_context():
        try: user_count = User.query.count()
        except: pass
        
    # Get Healing Stats (from logs)
    healing_count = 0
    events_file = Config.NEXUS_EVENTS_LOG
    if os.path.exists(events_file):
        try:
            with open(events_file, 'r', encoding='utf-8') as f:
                for line in f:
                    if '"name": "CONTAINER_' in line or '"name": "LOG_ROTATION"' in line:
                        healing_count += 1
        except: pass

    master_path = os.path.join(Config.BASE_PATH, "berichte", "Komplett-Status.md")
    os.makedirs(os.path.dirname(master_path), exist_ok=True)
    
    master_content = f"""# Shinra_Gate – Komplett-Status & Sicherheits-Audit
**Letztes Update**: {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

## 🛡️ Taktischer Sicherheits-Bericht (Letzte 7 Tage)
- **Audit-Zeitraum**: {cutoff.strftime('%Y-%m-%d')} bis {datetime.now().strftime('%Y-%m-%d')}
- **Erfolgreiche Logins**: {stats['reqs']}
- **Fehlgeschlagene Versuche**: {stats['fails']}
- **Eindeutige Angreifer-IPs**: {len(stats['ips'])}

### 🔴 Autonome Abwehrmaßnahmen
P.I.G.E.O.N. hat alle erkannten Bedrohungen erfolgreich neutralisiert. 
Sperren wurden basierend auf Brute-Force-Heuristiken verhängt.

---

## 🧠 Guardian Integrity System (v16.1)
- **Status**: AKTIV & OPERATIV
- **Heilungs-Events**: {healing_count} (Gesamt-Historie)
- **Log Maintenance**: Aktiv (5MB Rotation Threshold)

---

## 👥 User Matrix & Access Control
- **Registrierte User**: {user_count}
- **Auth-System**: Datenbank-Hashed (Active)

---

## 📡 Strategische Einschätzung
Systemstatus: **NOMINAL**
Integrität: **VERIFIZIERT**

---
*Bericht automatisch konsolidiert von P.I.G.E.O.N. Intelligence Engine*
"""
    with open(master_path, 'w', encoding='utf-8') as f:
        f.write(master_content)
